---
- name: Workflow generator for Build statge of DevSecOps pipeline
  hosts: localhost
  vars:
    stage: build  

  tasks:
  - name: create workflow for pipeline run
    - name: Create a workflow job template with workflow nodes in template
  awx.awx.workflow_job_template:
    name: Build
    inventory: Demo Inventory
    workflow_nodes:
      - identifier: synchronize
        unified_job_template:
          name: Synchronize latest version of pipeline
          organization:
            name: Default
          name: Build  
          type: project-sync
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes: []
          credentials: []
      - identifier: jenkinsbuild
        unified_job_template:
          organization:
            name: Default
          name: Jenkind - Build
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: synchronize
          failure_nodes: []
          always_nodes: []
          credentials: []
      - identifier: tcoebuild
        unified_job_template:
          organization:
            name: Default
          name: TCOE - Build
          type: job_template
        related:
          success_nodes: 
            - identifier: jenkinsbuild
          failure_nodes: []
          always_nodes: []
          credentials: []
      - identifier: artifactorybuild
        unified_job_template:
          organization:
            name: Default
          name: Artifactory - Built
          type: workflow_job_template
        related:
          success_nodes: 
            - identifier: tcoebuild
          failure_nodes: []
          always_nodes: []
          credentials: []
  register: result 




