---
- name: Workflow generator for Build stage of DevSecOps pipeline
  hosts: localhost
  vars:
    stage: build  

  tasks:
  - name: create workflow for Build pipeline run
    awx.awx.workflow_job_template:
      name: Build
      inventory: Demo Inventory
      extra_vars: '{ stage: build }'
      workflow_nodes:
        - identifier: synchronize
          unified_job_template:
            name: Synchronize latest version of pipeline
            organization:
              name: Default
            name: Build  
            type: project-sync
          related:
            success_nodes: jenkinsbuild
            failure_nodes: []
            always_nodes: []
            credentials: []
        - identifier: jenkinsbuild
          unified_job_template:
            organization:
              name: Default
            name: Jenkins - Build
            type: job_template
          credentials: []
          related:
            success_nodes:
              - identifier: autbuild
            failure_nodes: []
            always_nodes: []
            credentials: []
        - identifier: autbuild
          unified_job_template:
            organization:
              name: Default
            name: SonarQube AUT - Build
            type: job_template
          related:
            success_nodes: 
              - identifier: securitybuild
            failure_nodes: []
            always_nodes: []
            credentials: []
        - identifier: securitybuild
          unified_job_template:
            organization:
              name: Default
            name: Security - Build
            type: workflow_template
          related:
            success_nodes:
              - identifier: artifactorybuild
            failure_nodes: []
            always_nodes: []
            credentials: []

        - identifier: artifactorybuild
          unified_job_template:
            organization:
              name: Default
            name: Artifactory - Build
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: []
            credentials: []
    register: result 




